"""A "runs from a fresh clone" claim must match what a fresh clone can do.

The README promised unqualified fresh-clone reproduction in four places. It was
false in two of them: `data/external/` is gitignored, so the F1 breadth layer,
F1 reliability and WEC reliability cannot be regenerated by anyone who clones
this repository. Their outputs are committed, so every test and every downstream
consumer runs offline — what is blocked is rebuilding them from source.

That distinction is easy to lose and expensive to lose: it is the first thing a
reviewer checks, and being wrong about it costs more credibility than the
limitation itself ever would.

These guards are structural rather than textual. They do not try to parse
English — they check that the set of scripts reading `data/external/` is exactly
the set documented as blocked, so adding a fourth one fails here instead of
silently making a published claim false.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
EXTERNAL_DOC = REPO / "data" / "external" / "README.md"

#: Scripts known to read third-party data this repository does not ship. Each
#: must appear in the acquisition document with what it reads and what it
#: writes, so a reader can obtain the input or understand why they cannot.
BLOCKED_SCRIPTS = frozenset({
    "run_f1_history_degradation.py",
    "run_f1_reliability.py",
    "run_wec_reliability.py",
})

#: Reads `data/external/` only to describe it. It produces no artifact, so it
#: makes no reproduction claim and belongs in neither set.
INSPECTION_ONLY = frozenset({"inspect_external.py"})


def _scripts_reading_external() -> set[str]:
    """Every script under scripts/ that touches data/external/."""
    found = set()
    for script in (REPO / "scripts").glob("*.py"):
        text = script.read_text(encoding="utf-8", errors="replace")
        if re.search(r"data/external|external[/\\](f1|wec)", text):
            found.add(script.name)
    return found - INSPECTION_ONLY


def test_the_acquisition_document_exists() -> None:
    """Without it, a reader who cannot regenerate a layer has nowhere to go."""
    assert EXTERNAL_DOC.exists(), (
        f"{EXTERNAL_DOC.relative_to(REPO)} is missing. Three layers depend on "
        "data this repository does not ship; the document naming them is the "
        "only thing standing between that and an unexplained failure."
    )


def test_no_undocumented_script_depends_on_external_data() -> None:
    """A new external dependency must be declared, not discovered later."""
    actual = _scripts_reading_external()
    undocumented = sorted(actual - BLOCKED_SCRIPTS)
    assert not undocumented, (
        f"these scripts read data/external/ but are not declared blocked: "
        f"{undocumented}. Add each to BLOCKED_SCRIPTS here and to the table in "
        "data/external/README.md, and check whether any 'runs from a fresh "
        "clone' claim in README.md now needs qualifying. A layer that silently "
        "stops being reproducible is the defect this file exists to prevent."
    )


def test_no_declared_script_has_quietly_become_self_contained() -> None:
    """The reverse drift: a limitation documented after it stopped being true.

    If a script no longer needs external data, the claim it forced us to
    qualify should be un-qualified — an over-cautious caveat is a smaller
    problem than a false promise, but it is still wrong.
    """
    actual = _scripts_reading_external()
    stale = sorted(BLOCKED_SCRIPTS - actual)
    assert not stale, (
        f"these scripts are declared blocked but no longer read "
        f"data/external/: {stale}. If they became self-contained, remove them "
        "from BLOCKED_SCRIPTS and from data/external/README.md, and restore "
        "the plain reproduction claim they were forcing us to qualify."
    )


@pytest.mark.parametrize("script", sorted(BLOCKED_SCRIPTS))
def test_each_blocked_script_is_named_in_the_document(script: str) -> None:
    """A reader hitting the failure must find that script by name."""
    text = EXTERNAL_DOC.read_text(encoding="utf-8")
    assert script in text, (
        f"{script} reads data/external/ but is not named in "
        f"{EXTERNAL_DOC.relative_to(REPO)}. Someone whose run fails on a "
        "missing file needs to find it there."
    )


def test_the_two_qualified_claims_still_carry_their_qualification() -> None:
    """The exact sentences that were false, pinned to stay honest.

    Textual rather than structural, and narrow on purpose: it watches the two
    table rows that made the promise, not every use of the phrase. IMSA and
    ELMS keep theirs unqualified because neither reads external data — an
    accuracy worth preserving, since a blanket caveat everywhere would make the
    two real limitations invisible.
    """
    readme = (REPO / "README.md").read_text(encoding="utf-8")
    rows = [
        line for line in readme.splitlines()
        if "Runs from a fresh clone" in line
    ]
    assert rows, "no fresh-clone claim found in README.md at all — did the table move?"

    unqualified = [
        line for line in rows
        if "data/external/README.md" not in line
        and not any(series in line for series in ("imsa/", "elms/"))
    ]
    assert not unqualified, (
        "these fresh-clone claims cover a series with a blocked layer but do "
        f"not point at the exception: {unqualified}. F1 (breadth, reliability) "
        "and WEC (reliability) cannot be regenerated from a clone; a claim "
        "that says otherwise is the first thing a reviewer will check and the "
        "cheapest possible way to lose their trust."
    )
