"""The committed endurance model artifacts (regenerated by
scripts/run_endurance_models.py) must cover the full scope, stay consistent
with a fresh recomputation (no drift between code and the CSVs), and back the
specific numeric claims the hand-written reports make."""

from __future__ import annotations

import pandas as pd
import pytest

from src.data.endurance_loader import EnduranceLoader
from src.data.endurance_scope import scoped_race_seasons
from src.degradation.endurance import build_endurance_frame, fit_endurance_degradation
from src.ingestion.config import ENDURANCE_DERIVED_DIR


@pytest.fixture(scope="module")
def fits() -> pd.DataFrame:
    return pd.read_csv(ENDURANCE_DERIVED_DIR / "endurance_degradation_fits.csv")


@pytest.fixture(scope="module")
def loro() -> pd.DataFrame:
    return pd.read_csv(ENDURANCE_DERIVED_DIR / "endurance_degradation_loro.csv")


def test_artifacts_cover_the_full_scope(fits) -> None:
    assert len(fits) == len(scoped_race_seasons())  # one row per circuit-season
    assert set(fits["series"]) == {"imsa", "wec"}


def test_committed_fits_match_a_fresh_recomputation(fits) -> None:
    """Guard against drift: regenerate two circuit-seasons and check the
    committed CSV still matches, so the artifacts can't silently go stale."""
    for series, event, cls, season in (("wec", "Bahrain", "HYPERCAR", 2024),
                                        ("imsa", "Road America", "GTP", 2024)):
        fresh = fit_endurance_degradation(
            build_endurance_frame(EnduranceLoader(series).load_laps(season, event, cls))
        )
        row = fits[(fits["series"] == series) & (fits["event"] == event)
                   & (fits["season"] == season)].iloc[0]
        assert row["net_slope"] == pytest.approx(round(fresh.net_slope.value, 4), abs=1e-4)
        assert row["rmse_s"] == pytest.approx(round(fresh.rmse_s, 3), abs=1e-3)


def test_separability_claim_matches_the_report(fits) -> None:
    """The IMSA report claims 9 of 10 IMSA race-seasons are non-separable, with
    Sebring 2025 the lone exception, and all WEC race-seasons non-separable."""
    imsa = fits[fits["series"] == "imsa"]
    wec = fits[fits["series"] == "wec"]
    assert (~imsa["separable"]).sum() == len(imsa) - 1
    lone = imsa[imsa["separable"]]
    assert list(zip(lone["event"], lone["season"])) == [("Sebring", 2025)]
    assert (~wec["separable"]).all()


def test_loro_backs_the_bahrain_exception(loro) -> None:
    """The WEC report's headline exception: Bahrain's slope genuinely transfers
    across seasons (mean LORO R2 well positive), unlike Watkins Glen."""
    bahrain = loro[(loro["event"] == "Bahrain") & (loro["held_out_season"] == "MEAN")]
    glen = loro[(loro["event"] == "Watkins Glen") & (loro["held_out_season"] == "MEAN")]
    assert float(bahrain["r2_within"].iloc[0]) > 0.15
    assert float(glen["r2_within"].iloc[0]) < 0.05
