"""The committed endurance model artifacts (regenerated by
scripts/run_endurance_models.py) must cover the full scope, stay consistent
with a fresh recomputation (no drift between code and the CSVs), and back the
specific numeric claims the hand-written reports make."""

from __future__ import annotations

import pandas as pd
import pytest

from src.data.endurance_loader import EnduranceLoader
from src.data.endurance_scope import scoped_race_seasons
from src.degradation.endurance import build_endurance_frame, fit_endurance_degradation
from src.ingestion.config import ENDURANCE_DERIVED_DIR


@pytest.fixture(scope="module")
def fits() -> pd.DataFrame:
    return pd.read_csv(ENDURANCE_DERIVED_DIR / "endurance_degradation_fits.csv")


@pytest.fixture(scope="module")
def loro() -> pd.DataFrame:
    return pd.read_csv(ENDURANCE_DERIVED_DIR / "endurance_degradation_loro.csv")


def test_artifacts_cover_the_full_scope(fits) -> None:
    assert len(fits) == len(scoped_race_seasons())  # one row per circuit-season
    # Asserted as a superset-of-the-known rather than an exact set: the scope
    # grows as series and classes are added (ELMS joined IMSA and WEC), and an
    # exact match would fail on every widening for no reason. What must hold is
    # that nothing modelled has silently vanished.
    assert {"imsa", "wec"} <= set(fits["series"])


def test_committed_fits_match_a_fresh_recomputation(fits) -> None:
    """Guard against drift: regenerate two circuit-seasons and check the
    committed CSV still matches, so the artifacts can't silently go stale."""
    for series, event, cls, season in (("wec", "Bahrain", "HYPERCAR", 2024),
                                        ("imsa", "Road America", "GTP", 2024)):
        fresh = fit_endurance_degradation(
            build_endurance_frame(EnduranceLoader(series).load_laps(season, event, cls))
        )
        row = fits[(fits["series"] == series) & (fits["event"] == event)
                   & (fits["season"] == season)].iloc[0]
        assert row["net_slope"] == pytest.approx(round(fresh.net_slope.value, 4), abs=1e-4)
        assert row["rmse_s"] == pytest.approx(round(fresh.rmse_s, 3), abs=1e-3)


def test_separability_claim_matches_the_report(fits) -> None:
    """The fuel/degradation split is identified almost nowhere, and where it is,
    the reason is the race format rather than the car.

    Stated per class, because the claim is about *races* and a class is part of
    what a race is: pooling GTP and GTD Sebring rows would have made "Sebring
    is separable at both editions" read as four editions of one thing.

    IMSA GTP: Sebring 2025 and 2026, whose 12 h format has enough fuel-only
    splash stops to weaken the usual fuel/tyre collinearity, plus Indianapolis
    2024 sitting 0.003 the right side of a 0.90 cutoff — named as the threshold
    coincidence it is, not as a second finding. Every WEC race stays
    non-separable.
    """
    gtp = fits[(fits["series"] == "imsa") & (fits["car_class"] == "GTP")]
    wec = fits[fits["series"] == "wec"]
    separable_gtp = gtp[gtp["separable"]]
    assert set(separable_gtp["event"]) == {"Sebring", "Indianapolis"}
    sebring = separable_gtp[separable_gtp["event"] == "Sebring"]
    assert len(sebring) == 2
    assert (sebring["fuel_deg_corr"] < 0.85).all()
    indy = separable_gtp[separable_gtp["event"] == "Indianapolis"]
    assert len(indy) == 1 and (indy["fuel_deg_corr"] > 0.89).all()
    assert (~wec["separable"]).all()

    # GT3 is reported in its own right; the collinearity is the norm there too.
    gtd = fits[(fits["series"] == "imsa") & (fits["car_class"] == "GTD")]
    assert len(gtd) > 50
    assert gtd["separable"].mean() < 0.25, "GT3 should be mostly non-separable too"


def test_loro_backs_the_bahrain_exception(loro) -> None:
    """The WEC report's headline exception: Bahrain's slope genuinely transfers
    across seasons (mean LORO R2 well positive), unlike Watkins Glen."""
    bahrain = loro[(loro["event"] == "Bahrain") & (loro["held_out_season"] == "MEAN")]
    glen = loro[(loro["event"] == "Watkins Glen") & (loro["held_out_season"] == "MEAN")]
    assert float(bahrain["r2_within"].iloc[0]) > 0.15
    assert float(glen["r2_within"].iloc[0]) < 0.05


def test_endurance_overtaking_difficulty_is_measured_and_stable() -> None:
    """Track-position value reaches WEC/IMSA too (position reconstructed from
    cumulative time). Values must be physical and the committed artifact must
    match a fresh recomputation for a sample circuit."""
    from src.data.endurance_loader import EnduranceLoader
    from src.data.endurance_scope import ENDURANCE_SCOPE
    from src.simulator.track_position import (
        adjacent_swap_rate_endurance,
        measure_circuit,
    )

    art = pd.read_csv(ENDURANCE_DERIVED_DIR / "endurance_overtaking_difficulty.csv")
    assert {"imsa", "wec"} <= set(art["series"])
    assert art["adj_swap_rate"].between(0.0, 0.15).all()  # physical
    assert (art["p_hold_15_laps"].between(0.0, 1.0)).all()

    # Drift guard: recompute one circuit (whichever sits at this scope index —
    # any circuit works, the assertion below is dynamic) and match the
    # committed value.
    cs = ENDURANCE_SCOPE["wec"][2]
    races = {str(y): EnduranceLoader("wec").load_laps(y, cs.event, cs.car_class)
             for y in cs.seasons}
    fresh = measure_circuit(races, cs.event, rate_fn=adjacent_swap_rate_endurance)
    row = art[(art["series"] == "wec") & (art["circuit"] == cs.event)].iloc[0]
    assert row["adj_swap_rate"] == pytest.approx(round(fresh.swap_rate, 4), abs=1e-4)


def test_pit_procedure_confirms_the_wec_sequential_rule() -> None:
    """WEC changes tyres only after the fuel hose is out (sequential), IMSA does
    both at once (parallel), so WEC's tyre-change premium must be far larger.
    Both a data-backed claim and a drift guard on the committed artifact.

    Compared **like class against like class** — WEC HYPERCAR against IMSA
    GTP, both top prototypes. The premium is a rulebook effect in kind but a
    car property in magnitude, so pooling IMSA's GTD in with its GTP would
    average a GT3 tyre service into a prototype's and answer a question nobody
    asked. That pooling was invisible while each series had one class in scope.
    """
    proc = pd.read_csv(ENDURANCE_DERIVED_DIR / "endurance_pit_procedure.csv")
    assert "car_class" in proc.columns, "the premium must be reported per class"
    prem = proc.set_index(["series", "car_class"])["tyre_change_premium_s"]
    imsa_prem = float(prem[("imsa", "GTP")])
    wec_prem = float(prem[("wec", "HYPERCAR")])
    assert 0 < imsa_prem < 15          # tyres largely hidden behind the fuel fill
    assert wec_prem > 18               # full tyre service added on top
    # Bound loosened on the widened scope (2.5x -> 2.0x): the pooled ratio is
    # ~2.5x on 33 IMSA + 28 WEC prototype races, still a clear procedural gap.
    assert wec_prem > 2.0 * imsa_prem  # the procedural difference, quantified

    # GTD is measured in its own right rather than folded into GTP.
    assert ("imsa", "GTD") in prem.index
    assert float(prem[("imsa", "GTD")]) > 0


# --- class identity, now carried rather than assumed away --------------------


def test_artifacts_identify_the_car_class() -> None:
    """A race-season is not identified by (series, event, season) alone.

    A series can field more than one class at the same event — IMSA runs GTP
    and GTD at every round — so without a class column two classes' rows are
    indistinguishable on every key a consumer would naturally merge or filter
    on. ``run_multistop.py`` additionally keyed its results by
    (series, event) and would have kept only whichever class came last.

    Pinned because the failure is silent in both directions: nothing errors,
    a row simply describes a different car than the reader thinks. This is
    the prerequisite for scoping IMSA GTD alongside GTP
    (``reports/new_series_survey_phase0.md``).
    """
    for name in ("endurance_degradation_fits.csv", "multistop_plans.csv",
                 "endurance_data_quality.csv", "endurance_degradation_loro.csv",
                 "endurance_overtaking_difficulty.csv"):
        art = pd.read_csv(ENDURANCE_DERIVED_DIR / name)
        assert "car_class" in art.columns, f"{name} does not identify the car class"
        assert art["car_class"].notna().all(), f"{name} has rows with no class"


def test_every_artifact_row_is_uniquely_keyed_with_the_class() -> None:
    """With the class in the key, one row per (series, event, class, season).

    The point of the previous test is only realised if the extended key is
    actually unique — a class column that still leaves duplicates would look
    like a fix while changing nothing.
    """
    fits = pd.read_csv(ENDURANCE_DERIVED_DIR / "endurance_degradation_fits.csv")
    key = ["series", "event", "car_class", "season"]
    assert not fits.duplicated(key).any(), fits[fits.duplicated(key, keep=False)][key]

    plans = pd.read_csv(ENDURANCE_DERIVED_DIR / "multistop_plans.csv")
    plan_key = ["series", "circuit", "car_class"]
    assert not plans.duplicated(plan_key).any()


def test_scope_has_no_literally_duplicated_entry() -> None:
    """The real invariant, arrived at after getting it wrong twice.

    The first version forbade any two event strings mapping to one circuit.
    That blocks a *rename*: covering Canadian Tire Motorsport Park (2026)
    means scoping it beside Mosport, because the source renamed the track.

    The second version allowed renames but forbade two names for one circuit
    in the same season, on the theory that this meant a duplicated race. It
    does not: IMSA ran two races at Watkins Glen in 2021, and the source names
    them separately — ``Watkins Glen 240`` is 57 laps and 12 cars, ``Watkins
    Glen 6 Hours`` is 179 laps and 14. Two distinct races at one track in one
    year, both legitimate.

    Both versions encoded a *supposed consequence* instead of the invariant.
    The invariant was never "one name per circuit-season"; it is that
    validation folds group on the **canonical circuit**, which
    ``circuit_canonical`` in every artifact now carries and
    ``test_artifacts_carry_a_canonical_circuit_identity`` checks. What is left
    to assert here is only that no entry is literally repeated — the same
    series, event and class scoped twice, which would load the same laps twice
    for no reason.
    """
    from src.data.endurance_scope import ENDURANCE_SCOPE

    seen: set[tuple[str, str, str]] = set()
    for series, circuits in ENDURANCE_SCOPE.items():
        for cs in circuits:
            key = (series, cs.event, cs.car_class)
            assert key not in seen, f"{key} is scoped more than once"
            seen.add(key)


def test_artifacts_carry_a_canonical_circuit_identity() -> None:
    """Validation folds must group on the circuit, not on the source's string.

    ``circuit``/``event`` stays the name the upstream data uses, so a row can
    still be traced to the file it came from; ``circuit_canonical`` is the
    identity a leave-one-circuit-out fold has to group on. They differ only
    where a track was renamed upstream — today nowhere, which is why this can
    be added without moving a single number, and exactly why it should be
    added now rather than in the same change that first scopes an alias.
    """
    from src.data.endurance_scope import canonical_circuit

    for name, src in (("endurance_degradation_fits.csv", "event"),
                      ("endurance_data_quality.csv", "event"),
                      ("endurance_degradation_loro.csv", "event"),
                      ("endurance_overtaking_difficulty.csv", "circuit"),
                      ("multistop_plans.csv", "circuit")):
        art = pd.read_csv(ENDURANCE_DERIVED_DIR / name)
        assert "circuit_canonical" in art.columns, f"{name} has no canonical circuit"
        assert art["circuit_canonical"].notna().all()

    # And it must actually be the canonical map's output, not a copy of the
    # source column that would silently stop tracking it.
    fits = pd.read_csv(ENDURANCE_DERIVED_DIR / "endurance_degradation_fits.csv")
    expected = fits["event"].map(canonical_circuit)
    assert (fits["circuit_canonical"] == expected).all()
