"""Phase 0 data availability check.

Loads every candidate (season, grand prix) race session through FastF1 and
records what the data actually contains: lap counts, tyre compounds, pit
stops, track-status coverage (needed for the SC/VSC model) and weather rows.

Nothing here is estimated — every number in the output comes from a real
session load. Results are written to ``reports/data_availability_phase0.md``
and printed to stdout so the circuit/season selection in the README can be
justified with verified facts instead of assumptions.

Usage (from the repo root)::

    python scripts/check_data_availability.py
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path

import fastf1
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
CACHE_DIR = REPO_ROOT / "data" / "cache"
REPORT_PATH = REPO_ROOT / "reports" / "data_availability_phase0.md"

#: Candidate seasons: the three most recent completed seasons, all inside the
#: 2022-2025 ground-effect regulation era so car behaviour is comparable.
SEASONS: tuple[int, ...] = (2023, 2024, 2025)

#: Candidate circuits chosen to contrast safety-car risk and tyre stress:
#: two street circuits with historically high SC rates (Monaco, Singapore),
#: one low-SC permanent circuit that is also tyre-limited (Barcelona), and
#: one low-SC high-load permanent circuit (Suzuka).
GRANDS_PRIX: tuple[str, ...] = ("Monaco", "Singapore", "Spanish", "Japanese")

# FastF1 track status codes (per FastF1 docs / livetiming feed).
SC_CODE = "4"
RED_FLAG_CODE = "5"
VSC_CODE = "6"


@dataclass
class SessionCheck:
    """Result of probing one race session for data availability."""

    season: int
    grand_prix: str
    event_name: str = ""
    ok: bool = False
    error: str = ""
    total_laps: int = 0
    accurate_laps: int = 0
    drivers: int = 0
    compounds: str = ""
    pit_stops: int = 0
    track_status_rows: int = 0
    sc_periods: int = 0
    vsc_periods: int = 0
    red_flags: int = 0
    weather_rows: int = 0
    notes: list[str] = field(default_factory=list)


def _count_status_periods(track_status: pd.DataFrame, code: str) -> int:
    """Count distinct periods during which ``code`` appears in the track status.

    The livetiming feed emits one row per status *change*; a status string can
    contain several codes at once (e.g. ``"24"`` = yellow + SC). A "period"
    is a maximal run of consecutive rows whose status contains the code.
    """
    if track_status.empty:
        return 0
    active = track_status["Status"].astype(str).str.contains(code, regex=False)
    # A period starts wherever `active` flips from False to True.
    starts = active & ~active.shift(1, fill_value=False)
    return int(starts.sum())


def check_session(season: int, grand_prix: str) -> SessionCheck:
    """Load one race session and record what data is actually available."""
    result = SessionCheck(season=season, grand_prix=grand_prix)
    try:
        session = fastf1.get_session(season, grand_prix, "R")
        session.load(laps=True, telemetry=False, weather=True, messages=True)
    except Exception as exc:  # noqa: BLE001 - report any load failure verbatim
        result.error = f"{type(exc).__name__}: {exc}"
        return result

    result.event_name = str(session.event["EventName"])
    laps = session.laps
    result.ok = True
    result.total_laps = len(laps)
    result.accurate_laps = int(laps["IsAccurate"].sum())
    result.drivers = laps["Driver"].nunique()
    compounds = sorted(c for c in laps["Compound"].dropna().unique() if c)
    result.compounds = "/".join(compounds)
    result.pit_stops = int(laps["PitInTime"].notna().sum())

    track_status = session.track_status
    if track_status is None or len(track_status) == 0:
        result.notes.append("NO TrackStatus data")
    else:
        result.track_status_rows = len(track_status)
        result.sc_periods = _count_status_periods(track_status, SC_CODE)
        result.vsc_periods = _count_status_periods(track_status, VSC_CODE)
        result.red_flags = _count_status_periods(track_status, RED_FLAG_CODE)

    weather = session.weather_data
    result.weather_rows = 0 if weather is None else len(weather)

    if result.accurate_laps < 0.5 * max(result.total_laps, 1):
        result.notes.append("less than 50% laps flagged accurate")
    return result


def to_markdown(results: list[SessionCheck]) -> str:
    """Render all session checks as a markdown report."""
    lines = [
        "# Phase 0 — FastF1 data availability report",
        "",
        "Generated by `scripts/check_data_availability.py`. Every row is a real",
        "session load through FastF1 (laps + track status + weather, no telemetry).",
        "",
        "| Season | Event | Laps | Accurate laps | Drivers | Compounds | Pit stops | TrackStatus rows | SC | VSC | Red flags | Weather rows | Notes |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in results:
        if not r.ok:
            lines.append(
                f"| {r.season} | {r.grand_prix} | LOAD FAILED: {r.error} | | | | | | | | | | |"
            )
            continue
        notes = "; ".join(r.notes) if r.notes else ""
        lines.append(
            f"| {r.season} | {r.event_name} | {r.total_laps} | {r.accurate_laps} "
            f"| {r.drivers} | {r.compounds} | {r.pit_stops} | {r.track_status_rows} "
            f"| {r.sc_periods} | {r.vsc_periods} | {r.red_flags} | {r.weather_rows} | {notes} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    fastf1.Cache.enable_cache(str(CACHE_DIR))

    results: list[SessionCheck] = []
    for season in SEASONS:
        for gp in GRANDS_PRIX:
            print(f"Checking {season} {gp} ...", flush=True)
            results.append(check_session(season, gp))

    report = to_markdown(results)
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(report)
    failures = [r for r in results if not r.ok]
    print(f"\n{len(results) - len(failures)}/{len(results)} sessions loaded OK.")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
