"""Build the zip to upload to Overleaf.

There is no TeX distribution in this repository, so the manuscript has never
been compiled here. Overleaf is the first thing that will try it, and uploading
`paper/` on its own fails for a reason that is not obvious from the error:
Overleaf refuses any path containing "..", so `../reports/figures/x.png`
resolves to nothing and every figure comes back as a missing-file box.

This flattens the layout instead. The zip contains

    main.tex
    numbers.tex
    figures/*.png

and `\\graphicspath` in the manuscript lists `figures/` as a search root, so the
same `main.tex` compiles unchanged from `paper/` in a clone and from the root of
an Overleaf project.

The archive is byte-reproducible: entries are sorted and every timestamp is
fixed, so rebuilding it without changing an input produces an identical file and
a stale upload is visible as a differing checksum rather than invisible.

Usage (offline, from the repo root)::

    python scripts/make_paper_numbers.py      # refresh numbers.tex first
    python scripts/make_overleaf_bundle.py
"""

from __future__ import annotations

import hashlib
import re
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.ingestion.config import REPO_ROOT  # noqa: E402

PAPER = REPO_ROOT / "paper"
MAIN = PAPER / "main.tex"
OUT = PAPER / "overleaf.zip"

#: Fixed timestamp for every entry, so the archive depends on its contents and
#: nothing else. The value is arbitrary and only has to stay constant; zip
#: cannot store anything before 1980.
EPOCH = (1980, 1, 1, 0, 0, 0)


def graphics_roots(text: str) -> list[Path]:
    """The directories the manuscript declares for `\\includegraphics`."""
    match = re.search(r"\\graphicspath\{(.+?)\}\s*$", text, re.M)
    if not match:
        raise ValueError(
            "main.tex declares no \\graphicspath. Without it the figures "
            "cannot be flattened, because the inclusions give bare filenames."
        )
    return [PAPER / part for part in re.findall(r"\{([^{}]*)\}", match.group(1))]


def resolve_figures(text: str) -> dict[str, Path]:
    """Map each included filename to the file on disk, by the paper's own rules."""
    roots = graphics_roots(text)
    found: dict[str, Path] = {}
    for name in re.findall(r"\\includegraphics\[[^\]]*\]\{([^}]+)\}", text):
        for root in roots:
            candidate = (root / name).resolve()
            if candidate.exists():
                found[name] = candidate
                break
        else:
            raise FileNotFoundError(
                f"{name} is included by the paper but exists under none of "
                f"{[str(root) for root in roots]}. Run "
                "scripts/make_headline_figures.py and "
                "scripts/make_supporting_figures.py first."
            )
    if not found:
        raise ValueError("the paper includes no figures, which is not expected")
    return found


def build() -> Path:
    text = MAIN.read_text(encoding="utf-8")
    figures = resolve_figures(text)

    members: dict[str, Path] = {
        "main.tex": MAIN,
        "numbers.tex": PAPER / "numbers.tex",
    }
    for name, source in figures.items():
        members[f"figures/{name}"] = source

    missing = [name for name, path in members.items() if not path.exists()]
    if missing:
        raise FileNotFoundError(
            f"{missing} would be left out of the bundle. numbers.tex is "
            "generated by scripts/make_paper_numbers.py."
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as archive:
        for name in sorted(members):
            info = zipfile.ZipInfo(name, date_time=EPOCH)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, members[name].read_bytes())
    return OUT


def main() -> None:
    out = build()
    digest = hashlib.sha256(out.read_bytes()).hexdigest()
    with zipfile.ZipFile(out) as archive:
        names = archive.namelist()
    print(f"wrote {out.relative_to(REPO_ROOT)}  ({out.stat().st_size:,} bytes)")
    print(f"sha256 {digest}")
    for name in names:
        print(f"  {name}")
    print()
    print("Upload it at https://www.overleaf.com/project -> New Project -> "
          "Upload Project, then compile with pdfLaTeX.")


if __name__ == "__main__":
    main()
