"""Retrospective audit of the endurance multi-stop finding against real winners.

The models say every scoped endurance race is fuel-limited on stop count. This
replays that claim against reality: for each scoped circuit-season, reconstruct
the race winner's real fuel-stint lengths from the committed laps and test whether
they ran near the full fuel range. Agreement corroborates the finding; a winner
deliberately short-filling for tyres would refute it.

Offline (committed laps + the multistop fuel ranges). Writes
``data/derived/endurance/fuel_limited_audit.csv`` + ``reports/endurance_audit.md``.

Usage::

    python scripts/run_endurance_audit.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.audit.endurance_state import audit_fuel_limited  # noqa: E402
from src.data.endurance_loader import slugify  # noqa: E402
from src.data.endurance_scope import scoped_race_seasons  # noqa: E402
from src.ingestion.config import ENDURANCE_DERIVED_DIR, REPORTS_DIR  # noqa: E402

OUT_CSV = ENDURANCE_DERIVED_DIR / "fuel_limited_audit.csv"
OUT_REPORT = REPORTS_DIR / "cross_series" / "endurance_audit.md"


def _fuel_ranges() -> dict[tuple[str, str, str], int]:
    """(series, circuit slug, car class) -> fuel range in laps.

    **The class belongs in the key.** Without it this dict silently kept
    whichever row pandas iterated last, so an IMSA GTD race could be audited
    against GTP's fuel range — a different tank on a different car. That was
    already wrong when the multi-stop artifact held one row per circuit-class;
    it became wrong on every circuit once the artifact covered every
    race-season and the same key repeated across years.

    The median across a class's seasons is used because a fuel range is a
    property of the car and the circuit, not of one race: the artifact records
    it per race because it is *measured* per race, and a single season's
    estimate carries that race's noise.
    """
    plans = pd.read_csv(ENDURANCE_DERIVED_DIR / "multistop_plans.csv")
    grouped = plans.groupby(["series", "circuit", "car_class"])["fuel_range_laps"]
    return {key: int(round(value)) for key, value in grouped.median().items()}


def main() -> None:
    ranges = _fuel_ranges()
    rows = []
    missing: list[str] = []
    for series, event, car_class, season in scoped_race_seasons():
        circuit = slugify(event)
        fuel_range = ranges.get((series, circuit, car_class))
        if fuel_range is None:
            continue                                   # no fuel range measured
        # slugify, not .lower(): a class name can carry spaces and slashes
        # ("LMP2 Pro/Am" -> lmp2_pro_am). Lower-casing produced "lmp2 pro/am",
        # which matched no file, and the FileNotFoundError below swallowed the
        # whole class silently -- 17 ELMS race-seasons were missing from this
        # audit with nothing to show for it.
        slug = f"{season}_{circuit}_{slugify(car_class)}"
        try:
            audit = audit_fuel_limited(series, circuit, car_class, season, slug, fuel_range)
        except FileNotFoundError:
            missing.append(f"{series} {season} {event} {car_class}")
            continue
        rows.append(audit.row())

    if missing:
        # Loud, not silent: a class vanishing from this audit used to look
        # identical to a class that had no fuel range measured.
        print(f"  {len(missing)} scoped race-seasons had no lap file: "
              f"{missing[:5]}{' ...' if len(missing) > 5 else ''}")
    table = pd.DataFrame(rows)
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    table.to_csv(OUT_CSV, index=False)

    n = len(table)
    n_confirm = int(table["ran_fuel_limited"].sum())

    # Read from the plan table rather than restated: this opening asserted
    # "every scoped race is fuel-limited" for months after that stopped being
    # true, because it was prose and prose does not recompute.
    plans = pd.read_csv(ENDURANCE_DERIVED_DIR / "multistop_plans.csv")
    planned = len(plans)
    tyre_limited = int((plans["optimal_stops"] != plans["min_stops"]).sum())
    fuel_limited = planned - tyre_limited
    lines = [
        "<!-- GENERATED by scripts/run_endurance_audit.py — do not edit by hand. "
        "An earlier hand-correction to this file was silently overwritten by the "
        "next run; change the generator instead. -->",
        "",
        "# Retrospective audit — did endurance winners run fuel-limited?",
        "",
        f"The multi-stop model finds **{fuel_limited} of {planned}** planned "
        f"race-seasons fuel-limited on stop count and **{tyre_limited} "
        "tyre-limited**, the latter concentrated entirely in the cheap-stop "
        "classes (see the [WEC](../wec/simulator_phase4.md) / "
        "[IMSA](../imsa/gtp/simulator_phase4.md) / "
        "[ELMS](../elms/simulator_phase4.md) reports).",
        "",
        "This document once opened by saying *every* scoped race was "
        "fuel-limited. That was true of the prototype classes it was measured "
        "on and stated as a fact about endurance racing; "
        "[`when_tyres_beat_fuel.md`](when_tyres_beat_fuel.md) is what replaced "
        "it.",
        "",
        "The audit below tests the model against **what the race winners "
        "actually did**: their real fuel-stint lengths, reconstructed from the "
        "committed laps and compared to each circuit's measured fuel range. No "
        "number is quoted from memory.",
        "",
        f"**{n_confirm} of {n} audited winners ran fuel-limited** — at least one "
        "stint within 3 laps of the full fuel range, and a longest stint reaching "
        "it. Real winning behaviour corroborates the model's headline. **This "
        "exact share depends on that 3-lap tolerance** — see the "
        "[sensitivity sweep](fuel_limited_sensitivity.md), which reports it at "
        "every tolerance from 0 to 10 laps; the qualitative conclusion (a clear "
        "majority, in all three series) holds throughout, but the precise "
        "percentage should not be "
        "quoted alone — see "
        "[`fuel_limited_sensitivity.md`](fuel_limited_sensitivity.md) for the "
        "full sweep, including the per-series breakdown (IMSA moves more than "
        "WEC).",
        "",
        "| Series | Circuit | Year | Winner | Fuel range | Longest stint | Full stints | Verdict |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for _, r in table.iterrows():
        verdict = "fuel-limited" if r["ran_fuel_limited"] else "**tyre-limited?**"
        lines.append(
            f"| {r['series']} | {r['circuit']} | {int(r['year'])} | "
            f"{r['winner_car']} | {int(r['fuel_range_laps'])} | "
            f"{int(r['longest_stint'])} | {int(r['n_full_stints'])} | {verdict} |")
    lines += [
        "",
        "## Reading the exceptions",
        "",
        "A winner whose longest stint falls short of the fuel range is not "
        "automatically a refutation: a race disrupted by many neutralisations "
        "bunches stops and shortens stints for reasons unrelated to tyres. Where "
        "a winner *does* run a full-range stint, though, it is direct evidence "
        "that the tank — not the tyre — set the stint length, exactly as the DP "
        "concluded from the degradation and pit-loss numbers independently.",
    ]
    OUT_REPORT.parent.mkdir(parents=True, exist_ok=True)
    OUT_REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(table.to_string(index=False))
    print(f"\n{n_confirm}/{n} winners ran fuel-limited.")
    print(f"wrote {OUT_CSV}\nwrote {OUT_REPORT}")


if __name__ == "__main__":
    main()
