"""Per-class reports, generated from the artifacts rather than written by hand.

Every endurance class gets the same four documents covering **all** of its
race-seasons: lap accounting, fitted degradation, transfer validation, and
full-race strategy. Same structure, same discipline, whichever class it is.

This exists because the per-series reports were not per-class, and the gap was
not visible from reading them. ``reports/imsa/data_quality_phase1.md`` opens
"lap-level accounting for every scoped race-season" and accounts for **10**;
the artifact carries **140** across three classes. It never names a class, so
nothing in the prose says it is describing IMSA's GTP races only. GTD's 60
race-seasons and GTD PRO's 47 had no lap accounting anywhere.

The same was true one level down. The reports quoting per-race figures quoted
the handful their author had looked at, and there was no document in which a
reader could find, say, ELMS Portimao 2022's fitted slope and its interval.

Generating them fixes both problems at once, and a third that this project has
already paid for twice: **a generated report cannot go stale.** Every number
below is read from a committed CSV at build time, so a refit changes the
reports in the same commit that changes the data, and the staleness guards in
``tests/test_reports_are_not_stale.py`` have less to catch because there is
less prose carrying numbers by hand.

What is deliberately *not* generated: the interpretation. Each class keeps a
hand-written ``README.md`` for what its numbers mean, because that is the part
a generator cannot do and the part worth reading.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from src.ingestion.config import ENDURANCE_DERIVED_DIR, REPORTS_DIR

#: Directory name for each class, and the label used in prose.
CLASS_DIRS: dict[tuple[str, str], str] = {
    ("wec", "HYPERCAR"): "hypercar",
    ("imsa", "GTP"): "gtp",
    ("imsa", "GTD"): "gtd",
    ("imsa", "GTDPRO"): "gtdpro",
    ("elms", "LMP2"): "lmp2",
    ("elms", "LMP2 Pro/Am"): "lmp2_proam",
}

CLASS_LABELS: dict[tuple[str, str], str] = {
    ("wec", "HYPERCAR"): "WEC Hypercar",
    ("imsa", "GTP"): "IMSA GTP",
    ("imsa", "GTD"): "IMSA GTD",
    ("imsa", "GTDPRO"): "IMSA GTD PRO",
    ("elms", "LMP2"): "ELMS LMP2",
    ("elms", "LMP2 Pro/Am"): "ELMS LMP2 Pro/Am",
}

SERIES_LABELS = {"wec": "WEC", "imsa": "IMSA", "elms": "ELMS"}

#: Header carried by every generated file, so nobody edits one by hand and
#: loses the edit on the next run.
GENERATED = (
    "<!-- GENERATED by scripts/run_class_reports.py — do not edit by hand. "
    "Every number here is read from a committed artifact; change the data or "
    "the generator, not this file. -->"
)


@dataclass(frozen=True)
class ClassScope:
    series: str
    car_class: str

    @property
    def directory(self) -> Path:
        return REPORTS_DIR / self.series / CLASS_DIRS[(self.series, self.car_class)]

    @property
    def label(self) -> str:
        return CLASS_LABELS[(self.series, self.car_class)]

    def rows(self, frame: pd.DataFrame) -> pd.DataFrame:
        return frame[
            (frame["series"] == self.series) & (frame["car_class"] == self.car_class)
        ]


def _artifact(name: str) -> pd.DataFrame:
    return pd.read_csv(ENDURANCE_DERIVED_DIR / name)


def _fmt(value: float, places: int = 4, sign: bool = True) -> str:
    if pd.isna(value):
        return "—"
    return f"{value:+.{places}f}" if sign else f"{value:.{places}f}"


def data_quality(scope: ClassScope) -> str:
    """Lap accounting for every one of this class's race-seasons."""
    rows = scope.rows(_artifact("endurance_data_quality.csv")).sort_values(
        ["season", "circuit_canonical"]
    )
    total, kept = int(rows["total_laps"].sum()), int(rows["kept"].sum())

    lines = [
        GENERATED,
        "",
        f"# {scope.label} — data quality",
        "",
        f"Lap accounting for **all {len(rows)} race-seasons** of this class, one "
        "row each. Not a sample: the per-series version of this report accounted "
        "for the races its author had loaded, which for IMSA was 10 of 140.",
        "",
        f"**{total:,} raw laps, {kept:,} kept ({kept / total:.1%})**, "
        f"median {rows['pct_kept'].median():.1f}% per race.",
        "",
        "Each lap is dropped by exactly one stage, in this order, so the columns "
        "sum to the raw total:",
        "",
        "| stage | laps | what it removes |",
        "|---|---|---|",
        f"| non-green or pit | {int(rows['non_green_or_pit'].sum()):,} | "
        "neutralised, in-lap, out-lap |",
        f"| missing tyre age | {int(rows['missing_tyre_age'].sum()):,} | "
        "no stint reconstruction possible |",
        f"| field-wide trim | {int(rows['field_wide_trimmed'].sum()):,} | "
        "a lap the whole field ran slowly — a neutralisation ramp or standing "
        "start the flags missed |",
        f"| per-car trim | {int(rows['per_car_trimmed'].sum()):,} | "
        "each car's slowest residuals, after the first-pass fit |",
        f"| too few car laps | {int(rows['insufficient_car_laps'].sum()):,} | "
        "cars with too little running to carry a fixed effect |",
        "",
        "## Every race-season",
        "",
        "| season | circuit | raw | kept | % | non-green/pit | field-wide | per-car |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows.itertuples():
        lines.append(
            f"| {r.season} | {r.circuit_canonical} | {int(r.total_laps):,} | "
            f"{int(r.kept):,} | {r.pct_kept:.1f} | {int(r.non_green_or_pit):,} | "
            f"{int(r.field_wide_trimmed):,} | {int(r.per_car_trimmed):,} |"
        )
    return "\n".join(lines) + "\n"


def degradation(scope: ClassScope) -> str:
    """Every fitted slope, with its cluster-robust interval."""
    rows = scope.rows(_artifact("endurance_degradation_fits.csv")).sort_values(
        ["season", "circuit_canonical"]
    )
    negative = rows[rows["net_slope"] < 0]

    lines = [
        GENERATED,
        "",
        f"# {scope.label} — degradation",
        "",
        "    lap_time = a_{car,driver} + n · tyre_age + eps",
        "",
        "`n` is the **net within-stint slope**: tyre loss and fuel gain combined. "
        "Standard errors are cluster-robust by car with a `t(G−1)` reference, so "
        "an interval from a 7-car field is honestly wider than one from 20.",
        "",
        f"**{len(rows)} race-seasons.** Median net slope "
        f"**{_fmt(rows['net_slope'].median())} s/lap**, "
        f"steepest {_fmt(rows['net_slope'].max())}, "
        f"flattest {_fmt(rows['net_slope'].min())}.",
        "",
    ]

    if len(negative):
        worst = negative.loc[negative["net_slope"].idxmin()]
        lines += [
            f"**{len(negative)} of {len(rows)} fit a negative slope** — a tyre "
            "apparently gaining time as it ages, which is not a measurement. The "
            f"flattest is {worst['circuit_canonical']} {int(worst['season'])} at "
            f"{_fmt(worst['net_slope'])}. The cause is a diagnosed and unfixed "
            "omitted variable: the model carries no race-time term, so track "
            "evolution is attributed to tyre age with its sign inverted. Two "
            "corrections were built for it and both were withdrawn on real data "
            "— see [`track_evolution_omitted_variable.md`]"
            "(../../cross_series/track_evolution_omitted_variable.md).",
            "",
            "**Read every slope below as a lower bound on degradation.**",
            "",
        ]

    separable = int(rows["separable"].sum())
    lines += [
        f"Fuel and degradation are separable in **{separable} of {len(rows)}** "
        "races: teams change tyres at essentially every fuel stop, so "
        "`laps_since_refuel` and `tyre_age` move together after fixed effects "
        "and fitting both yields a collinear ridge. Only the net slope is "
        "reported.",
        "",
        "## Every fitted slope",
        "",
        "| season | circuit | net slope | 95% CI | RMSE | laps | cars |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows.itertuples():
        lines.append(
            f"| {r.season} | {r.circuit_canonical} | **{_fmt(r.net_slope)}** | "
            f"[{_fmt(r.ci_low)}, {_fmt(r.ci_high)}] | {r.rmse_s:.2f} s | "
            f"{int(r.n_laps):,} | {int(r.n_cars)} |"
        )
    return "\n".join(lines) + "\n"


def transfer(scope: ClassScope) -> str:
    """Leave-one-race-out: does a slope fitted on other seasons predict this one?"""
    rows = scope.rows(_artifact("endurance_degradation_loro.csv"))
    means = rows[rows["held_out_season"] == "MEAN"].sort_values("circuit_canonical")
    folds = rows[rows["held_out_season"] != "MEAN"]

    lines = [
        GENERATED,
        "",
        f"# {scope.label} — transfer between seasons",
        "",
        "Each season is held out in turn, a slope is pooled from that circuit's "
        "*other* seasons, and it is scored against the held-out season's own "
        "within-stint variance. A positive R² means the pooled slope carries "
        "information about a season it never saw; **zero or below means it "
        "carries none**, and a slope fitted here does not describe next year.",
        "",
    ]
    if means.empty:
        lines += ["No circuit in this class has enough seasons to hold one out.", ""]
        return "\n".join(lines) + "\n"

    positive = means[means["r2_within"] > 0.05]
    lines += [
        f"**{len(positive)} of {len(means)} circuits** transfer at all "
        f"(mean R² above +0.05). Best "
        f"{means['r2_within'].max():+.3f}, worst {means['r2_within'].min():+.3f}.",
        "",
        "## Mean within-stint R², per circuit",
        "",
        "| circuit | mean R² | folds |",
        "|---|---|---|",
    ]
    for r in means.itertuples():
        n = len(folds[folds["circuit_canonical"] == r.circuit_canonical])
        lines.append(f"| {r.circuit_canonical} | **{r.r2_within:+.3f}** | {n} |")

    lines += [
        "",
        "## Every fold",
        "",
        "| circuit | held out | pooled slope | own slope | R² |",
        "|---|---|---|---|---|",
    ]
    for r in folds.sort_values(["circuit_canonical", "held_out_season"]).itertuples():
        lines.append(
            f"| {r.circuit_canonical} | {r.held_out_season} | "
            f"{_fmt(r.pooled_slope)} | {_fmt(r.own_slope)} | {r.r2_within:+.3f} |"
        )
    return "\n".join(lines) + "\n"


def strategy(scope: ClassScope) -> str:
    """Full-race stop plans: the exact dynamic program, per race-season."""
    rows = scope.rows(_artifact("multistop_plans.csv")).sort_values(
        ["year", "circuit_canonical"]
    )
    if rows.empty:
        return (
            f"{GENERATED}\n\n# {scope.label} — strategy\n\n"
            "No full-race plan is materialised for this class.\n"
        )

    tyre_limited = rows[rows["optimal_stops"] != rows["min_stops"]]
    lines = [
        GENERATED,
        "",
        f"# {scope.label} — full-race strategy",
        "",
        "An exact dynamic program over every fuel-feasible stint partition, "
        "trading tyre degradation against pit loss, compared against the "
        "fuel-minimum baseline.",
        "",
        f"**{len(rows)} race-seasons planned.** Median pit loss "
        f"**{rows['pit_loss_s'].median():.1f} s**, median fuel range "
        f"{rows['fuel_range_laps'].median():.0f} laps.",
        "",
    ]
    if len(tyre_limited):
        lines += [
            f"**{len(tyre_limited)} of {len(rows)} are tyre-limited** — the "
            "optimum takes more stops than the fuel minimum, so degradation is "
            "steep enough relative to the stop cost that an extra stop pays:",
            "",
            "| season | circuit | pit loss | fuel minimum | optimum |",
            "|---|---|---|---|---|",
        ]
        for r in tyre_limited.itertuples():
            lines.append(
                f"| {r.year} | {r.circuit_canonical} | {r.pit_loss_s:.1f} s | "
                f"{int(r.min_stops)} | **{int(r.optimal_stops)}** |"
            )
        lines.append("")
    else:
        lines += [
            f"**None of the {len(rows)} is tyre-limited**: every one takes exactly "
            "its fuel-minimum stop count. The *break-even slope* below says how "
            "much steeper degradation would have to be to change that.",
            "",
        ]

    lines += [
        "## Every race-season",
        "",
        "| season | circuit | laps | pit loss | fuel range | min | optimal | "
        "break-even × |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows.itertuples():
        headroom = "—" if pd.isna(r.slope_headroom_x) else f"{r.slope_headroom_x:.1f}"
        flag = "" if r.optimal_stops == r.min_stops else " **"
        lines.append(
            f"| {r.year} | {r.circuit_canonical} | {int(r.race_laps)} | "
            f"{r.pit_loss_s:.1f} s | {int(r.fuel_range_laps)} | "
            f"{int(r.min_stops)} | {int(r.optimal_stops)}{flag} | {headroom} |"
        )
    return "\n".join(lines) + "\n"


#: File names say "all races" on purpose. Each class directory also holds
#: hand-written analysis, and a generated table called degradation.md next
#: to a hand-written degradation_phase2.md invites a reader to assume one
#: supersedes the other. These are the complete tables; the phase reports are
#: the argument built on them.
GENERATORS = {
    "data_quality_all_races.md": data_quality,
    "degradation_all_races.md": degradation,
    "transfer_all_races.md": transfer,
    "strategy_all_races.md": strategy,
}


def write_all(scopes: list[ClassScope] | None = None) -> list[Path]:
    """Generate every per-class report. Returns the paths written."""
    scopes = scopes or [ClassScope(s, c) for s, c in CLASS_DIRS]
    written: list[Path] = []
    for scope in scopes:
        scope.directory.mkdir(parents=True, exist_ok=True)
        for name, generator in GENERATORS.items():
            path = scope.directory / name
            path.write_text(generator(scope), encoding="utf-8")
            written.append(path)
    return written
